### ISSUE TITLE
Language list uses translated names while keyboard layout list uses english names

### ISSUE THREAD

**Issue by scootergrisen** [openSUSE/gfxboot#23]
I notice when i select language during boot in gfxboot the language names are translated.
Like it says "Dansk" my for language.

But then in keyboard selection list it uses english names like "Danish".

I would like the keyboard layout list to use the same translated names so both lists will say the same.

**Comment by wfeldt** [comment]
Note that this would require quite some translation effort. You'd have #languages x #keymaps translations to include.

Not sure that's worth it.

**Comment by scootergrisen** [comment]
Can you explain that?
I dont see why translating 41 strings would be a problem.

**Comment by wfeldt** [comment]
It's 41 keymaps x 48 languages = ca. 2000 strings.
