### ISSUE TITLE
New Sub Menu Module :: Menu Label Translations Broken

### ISSUE THREAD

**Issue by lots0logs** [openSUSE/gfxboot#5]
I can't see to get the new submenu module to use my translations for menu labels. It simply displays whatever you put in isolinux.cfg instead of using the value as an identifier to grab the proper translated string.

**Comment by wfeldt** [comment]
Hm, I thought I tested this. :-(

Will check.

**Comment by lots0logs** [comment]
Thanks..please let me know what you find!

**Comment by wfeldt** [comment]
Hm, it works for me. Note that you must not include the leading '->FOO'  tags in the translations.

**Comment by lots0logs** [comment]
Hmm..that is weird. I used [this](https://github.com/openSUSE/installation-images/blob/master/data/boot/syslinux.cfg) as a starting point and simply replaced whatever came after `->x` with my identifier string or whatever you want to call it :wink: It works fine for regular menu entries. Its just the sub menus that don't translate. :confused: 

Thanks for checking. I will give it another shot on next month's ISO build and see what happens

**Comment by wfeldt** [comment]
No problem.. If you have a small non-working test case, you can send it along.
