### ISSUE TITLE
"Error setting up gfxboot" on chromebooks

### ISSUE THREAD

**Issue by tjyrinki** [openSUSE/gfxboot#7]
It seems it's not possible to boot images using gfxboot on many/most Chromebooks with the RW_LEGACY boot option enabled, because the SeaBIOS used on those reuses existing framebuffer instead of reinitializing it.

For example Fedora 23 boots fine however.

Downstream bug http://pad.lv/1530530

**Comment by wfeldt** [comment]
So, as I understand it, a solution would be to keep the active video mode if it's a graphics mode?

**Comment by tjyrinki** [comment]
That sounds correct, even though I'm not an expert on these matters.

**Comment by wfeldt** [comment]
Ok, I've no chromebook, though. Could you test a fix?

**Comment by tjyrinki** [comment]
Sure.

**Comment by wfeldt** [comment]
Ok, I've opened a bug here: https://bugzilla.suse.com/980570; this makes it easier for me to track this and provide test isos. You don't need an account to access the bug.

Please try the test iso I attached there. Just 'dd' it to an unused usb stick. It will boot and list all available video modes.

My suspicion is that things are actually fine but the Chromebook has just an unusual selection of video modes. In this case we'll get away by just adjusting the gfxboot config file.

**Comment by tjyrinki** [comment]
Moved discussion and attachments there.

**Comment by siro20** [comment]
I think this issue can be marked as fixed

**Comment by tjyrinki** [comment]
Indeed.
